image:
  repository: ivicamaticsd/catapult-cs-stac-indexer
  tag: latest
  pullPolicy: Always

nats:
    host: "nats"
    port: 4222

s3:
    accessKeyId: "not-needed-s3-proxy"
    secretKeyId: "not-needed-s3-proxy"
    region: "eu-west-2"
    bucket: "ard-bucket"
    endpoint: "http://s3-proxy:80"
    imageryPath: "common_sensing"
    stacPath: "stac_catalogs/cs_stac"

db:
  # fill with flexible postgresql values
  hostname: ""
  username: ""
  password: ""
  database: ""
  port: ""