version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=datacube
      - DB_PORT=30002
      - NATS_HOST=localhost
      - NATS_PORT=30001
      - AWS_ACCESS_KEY_ID=not-needed
      - AWS_SECRET_ACCESS_KEY=not-needed
      - AWS_DEFAULT_REGION=eu-west-2
      - S3_ENDPOINT=http://localhost:30003
      - S3_BUCKET=ard-bucket
      - S3_IMAGERY_PATH=common_sensing
      - S3_STAC_PATH=stac_catalogs/cs_stac